services:
  trzsz:
    build: .
    container_name: trzsz-container
    ports:
      - "22234:22"
      - "22237:21"
    restart: unless-stopped
    networks:
      - trzsz-network
    privileged: true
    cap_add:
      - NET_ADMIN

networks:
  trzsz-network:
    driver: bridge
